---
repos:
    - repo: https://github.com/IamTheFij/docker-pre-commit
      rev: v2.0.0
      hooks:
          - id: hadolint-system
          - id: docker-compose-check
#    - repo: https://github.com/syntaqx/git-hooks
#      rev: v0.0.16
#      hooks:
#      # - id: forbid-binary
#      # - id: go-fmt
#      # - id: go-test
#      # - id: go-mod-tidy
#      # - id: go-generate
#          - id: shellcheck
#          - id: shfmt
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.1.0
      hooks:
          - id: yamlfmt
    - repo: https://github.com/adrienverge/yamllint
      rev: v1.25.0
      hooks:
          - id: yamllint
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.2.0
      hooks:
          - id: check-added-large-files
          - id: check-executables-have-shebangs
          - id: check-symlinks
          - id: check-merge-conflict
          - id: pretty-format-json
          - id: check-yaml
          - id: check-json
          - id: end-of-file-fixer
          - id: trailing-whitespace
          - id: detect-private-key
