---
version: '3.8'
x-logging: &default-logging
    driver: journald
    options:
        tag: '{{.Name}}'

x-utility:
    image: alpine:3.11
    logging: *default-logging
    networks:
        - default


services:
        #web:
        #        image: nginx:1.17.8
        #        container_name: web
        #        logging: *default-logging
        #        volumes:
        #                - ${PWD}/nginx:/etc/nginx
        #        restart: on-failure
        #        ports:
        #            - "80:80"
        #        stop_grace_period: 30s
        #        networks:
        #            net:
        #                ipv4_address: 10.254.1.2
    bitcoin:
        image: lncm/bitcoind:v0.20.1
        container_name: bitcoin
        depends_on: [tor]
        command:
            - -conf=/run/bitcoin/bitcoin.conf
                #healthcheck:
        logging: *default-logging
        volumes:
            - /srv/bitcoind:/data/.bitcoin
            - ${PWD}/bitcoin/bitcoin.conf:/run/bitcoin/bitcoin.conf:ro
            - /srv/tor/run:/srv/tor/run:ro
        restart: on-failure
        ports:
            - 8333:8333
            - 8332:8332
        stop_grace_period: 20m30s
        networks:
            net:
                ipv4_address: 10.254.2.2
        cap_drop:
            - ALL
    electrs:
        image: getumbrel/electrs:v0.8.5
        container_name: electrs
        depends_on:
            - tor
            - bitcoin
                #healthcheck:
        entrypoint:
            - electrs
        command:
            - --timestamp
            - --db-dir
            - /db
            - --daemon-dir
            - /bitcoin-data
            - --network
            - bitcoin
            - --electrum-rpc-addr
            - 0.0.0.0:50001
            - --daemon-rpc-addr
            - 10.254.2.2:8332
            - --monitoring-addr
            - 0.0.0.0:4224
            - --jsonrpc-import
            - --bulk-index-threads
            - '2'
            - --index-batch-size
            - '10'
            - --server-banner
            - Craig Wright is a Fraud
            - -vv
        cap_drop:
            - ALL
        ports:
            - 50001:50001
            - 4224:4224
        networks:
            net:
                ipv4_address: 10.254.2.7
        volumes:
            - /srv/bitcoind:/bitcoin-data:ro
            - /srv/electrs:/db
    electrs-ssl:
        image: primeroz/hitch:1.6.1-rc0
        container_name: electrs-ssl
        depends_on:
            - tor
            - electrs
                #healthcheck:
        environment:
            HITCH_PARAMS: --backend=[10.254.2.7]:50001 --frontend=[*]:50002
            DOMAIN: my.node.com
        cap_drop:
            - ALL
        cap_add:
            - SETUID
            - SETGID
        ports:
            - 50002:50002
        networks:
            net:
                ipv4_address: 10.254.2.8
    lnd:
        image: lncm/lnd:v0.11.1-monitoring
        container_name: lnd
        logging: *default-logging
        volumes:
            - /srv/lnd:/data/.lnd
            - ${PWD}/lnd/lnd.conf:/data/.lnd/lnd.conf:ro
            - /srv/bitcoind:/bitcoin-data:ro
        restart: on-failure
        ports:
            - "8989:8989" # Prometheus
            - "9735:9735" # P2P
            - "10009:10009" # RPC
        #depends_on: [ bitcoin, web ]
        depends_on: [ bitcoin, tor ]
        stop_grace_period: 10m30s
        networks:
            net:
                ipv4_address: 10.254.2.3
        #invoicer:
        #        image: "lncm/invoicer:v0.8.1"
        #        container_name: invoicer
        #        depends_on: [ bitcoin, lnd ]
        #        restart: on-failure
        #        stop_grace_period: 30s
        #        volumes:
        #                - "${PWD}/invoicer:/root/.lncm"
        #                - "${PWD}/invoicer:/data/.lncm"
        #                - "${PWD}/invoicer:/lncm"
        #                - "${PWD}/invoicer:/data"
        #                - "${PWD}/lnd:/lnd"
        #        networks:
        #            net:
        #                ipv4_address: 10.254.2.4
        #lnd-unlock:
        #        image: "lncm/lnd-unlock:1.0.0"
        #        container_name: lnd-unlock
        #        depends_on: [ lnd ]
        #        logging: *default-logging
        #        restart: always
        #        volumes:
        #            - "${PWD}/lnd:/lnd"
        #            - "${PWD}/secrets:/secrets"
        #        environment:
        #            NETWORK: mainnet
        #            LNDHOSTNAME: lnd
        #            HOSTIPPORT: 10.254.2.3:8080
        #        networks:
        #            net:
        #                ipv4_address: 10.254.2.5
        #neutrino-switcher:
        #        image: "lncm/neutrino-switcher:1.0.3"
        #        container_name: neutrino-switcher
        #        depends_on: [ lnd, bitcoin ]
        #        logging: *default-logging
        #        restart: always
        #        volumes:
        #            - "${PWD}/lnd:/lnd"
        #            - "${PWD}/secrets:/secrets"
        #            - "${PWD}/statuses:/statuses"
        #            - "/var/run/docker.sock:/var/run/docker.sock"
        #        environment:
        #            JSONRPCURL: http://10.254.2.2:8332
        #            LND_CONTAINER_NAME: lnd
        #            SLEEPTIME: 43200
        #        networks:
        #            net:
        #                ipv4_address: 10.254.2.6
    tor:
        image: lncm/tor:0.4.4.5
        container_name: tor
        restart: on-failure
        logging: *default-logging
        volumes:
            - ${PWD}/tor/torrc:/etc/tor/torrc
            - ${PWD}/tor/data:/var/lib/tor/
            - ${PWD}/tor/run:/var/run/tor/
            - /srv/tor:/srv/tor
        networks:
            net:
                ipv4_address: 10.254.1.3
        cap_drop:
            - ALL

networks:
    net:
        ipam:
            driver: default
            config:
                - subnet: 10.254.0.0/16
