FROM debian:buster@sha256:46d659005ca1151087efa997f1039ae45a7bf7a2cbbe2d17d3dcbda632a3ee9a

SHELL ["/bin/bash", "-c"]


RUN apt-get -yqq update \
 && apt-get -yqq upgrade \
 && apt-get -yqq install clang cmake curl git \
 && curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain 1.44.1 \
 && source /root/.cargo/env \
 && mkdir -p /srv/explorer/electrs{,_liquid} \
 && git clone --no-checkout https://github.com/blockstream/electrs.git \
 && cd electrs \
 && git checkout 2f8759e940a3fe56002d653c29a480ed3bffa416 \
 && cp contrib/popular-scripts.txt /srv/explorer \
 && cargo install --root /srv/explorer/electrs_bitcoin --locked --path . --features electrum-discovery \
 && cargo install --root /srv/explorer/electrs_liquid --locked --path . --features electrum-discovery,liquid \
 && cd .. \
 && rm -fr /root/.cargo electrs \
 && strip /srv/explorer/electrs_*/bin/electrs \
 && apt-get --auto-remove remove -yqq --purge clang cmake manpages curl git \
 && apt-get clean \
 && apt-get autoclean \
 && rm -rf /usr/share/doc* /usr/share/man /usr/share/postgresql/*/man /var/lib/apt/lists/* /var/cache/* /tmp/* /root/.cache /*.deb /root/.cargo
